### ISSUE TITLE
Action does not work

### ISSUE THREAD

**Issue by mishmanners** [ipc103/make-it-taylors-version#11] opened 2024-02-22 04:00 UTC
I added the file: https://github.com/mishmanners/GitHub-Like-A-Boss/blob/main/.github/workflows/taylorsversion.yml

I opened an issue: https://github.com/mishmanners/GitHub-Like-A-Boss/issues/126

The Action ran: https://github.com/mishmanners/GitHub-Like-A-Boss/actions/runs/7999221934

Error code:

[add-label](https://github.com/mishmanners/GitHub-Like-A-Boss/actions/runs/7999221934/job/21846673094)
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by dscho** [comment] 2024-02-22 07:36
> I opened an issue: [mishmanners/GitHub-Like-A-Boss#126](https://github.com/mishmanners/GitHub-Like-A-Boss/issues/126)

That item has number 126, but the workflow (it's not a GitHub Action, it's a GitHub workflow 😉) [specifically only targets item number 1989](https://github.com/ipc103/make-it-taylors-version/blob/main/.github/workflows/make-it-taylors-version.yml#L40).

**Comment by dscho** [comment] 2024-02-22 07:38
> it's not a GitHub Action, it's a GitHub workflow 😉

FWIW that could be easily addressed by turning it into [a composite GitHub Action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action).

**Comment by ipc103** [comment] 2024-02-22 14:14
👋 Hi @mishmanners! As @dscho mentioned, right now the action only updates the title if the number is 1989. I think we can add a config option to change this behavior. The fastest fix fro your case is to delete these lines from your workflow! https://github.com/mishmanners/GitHub-Like-A-Boss/blob/main/.github/workflows/taylorsversion.yml#L40-L42

**Comment by ipc103** [comment] 2024-02-22 14:34
Since this is currently expected behavior, closing in favor of #12

**Closed as completed by ipc103** 2024-02-22 14:34 UTC
